# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - urlsvc

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.x" # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Clean Project
        run: dotnet clean --configuration Release

      - name: Build .NET Project
        run: dotnet build --configuration Release --output ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D7AB2DAA72B84556B3F616D0CCC28276 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AADA1276EB364AF689E97BD2AB8D9EB6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_80A11F37156944CDBA6B414DF4EA288C }}

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "urlsvc"
          slot-name: "Production"
          package: "./publish" # Deploy the build output
